[package]
name = "irs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0", features = ["derive"]}

[dev-dependencies]
simple-pdf-parser = { path = "../simple-pdf-parser" }
simple-pdf-decrypt = { path = "../simple-pdf-decrypt" }
libflate = "2.0.0"

[features]
activate = []